
import streamlit as st
import pdfplumber
import re
from reportlab.pdfgen import canvas
from io import BytesIO
import datetime

st.set_page_config(page_title="AI Resume Analyzer", page_icon="📄")

st.title("📄 AI Resume Analyzer")
st.write("Upload your resume to analyze it.")

uploaded_file = st.file_uploader(
    "Upload Resume (PDF)",
    type=["pdf"]
)

def generate_pdf(email, phone, score, match_score, sections, missing):
    buffer = BytesIO()

    p = canvas.Canvas(buffer)
    p.rect(20,20,570,800)

    p.setFont("Helvetica-Bold", 16)
    p.drawString(50, 800, "AI Resume Analysis Report")

    p.setFont("Helvetica", 12)

    current_time = datetime.datetime.now().strftime("%d-%m-%Y %I:%M %p")
    p.drawString(50, 780, f"Generated On: {current_time}")
    y = 750

    p.drawString(50, y, f"Email: {email if email else 'Not Found'}")
    y -= 20

    p.drawString(50, y, f"Phone: {phone if phone else 'Not Found'}")
    y -= 20

    p.drawString(50, y, f"ATS Score: {score}/100")
    y -= 20

    p.drawString(50, y, f"Job Description Match: {match_score}%")
    y -= 30

    p.drawString(50, y, "Missing Sections:")
    y -= 20

    for section, keywords in sections.items():
        if any(keyword in text for keyword in keywords):
            p.drawString(70, y, f"✓ {section}")
        else:
            p.drawString(70, y, f"✗ {section}")
        y -= 20

    y -= 10
    p.drawString(50, y, "Missing Keywords:")
    y -= 20

    if missing:
        p.drawString(70, y, ", ".join(list(missing)[:10]))
    else:
        p.drawString(70, y, "None")

    p.setFont("Helvetica-Oblique", 10)
    p.drawString(180, 30, "Generated by AI Resume Analyzer")
    p.save()

    buffer.seek(0)
    return buffer

if uploaded_file is not None:

    text = ""

    with pdfplumber.open(uploaded_file) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text

    text = text.lower()

    st.subheader("📝 Job Description")
    job_description = st.text_area(
        "Paste the Job Description here",
        height=200
    )

    email = re.findall(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", text)
    phone = re.findall(r"\+?\d[\d\s-]{8,14}\d", text)
    email = email[0] if email else "Not Found"
    phone = phone[0] if phone else "Not Found"

    st.success("✅ Resume uploaded successfully!")

    st.subheader("Resume Preview")
    st.text(text[:1000])
    st.subheader("📧 Contact Details")

    if email:
        st.write("Email:", email)
    else:
        st.write("Email: Not Found")

    if phone:
        st.write("Phone:", phone)
    else:
        st.write("Phone: Not Found")

    st.subheader("🎓 Education")

    education = []

    keywords = [
        "B.tech",
        "BE",
        "b.sc",
        "M.tech",
        "ME",
        "m.sc",
        "MBA",
        "Anna University",
        "Bachelor Of Engineering",
        "Bachelor's Degree",
        "Bachelor Of Technology",
    ]

    if "bachelor of engineering" in text:
        st.write("✅ Bachelor of Engineering")
    elif "bachelor's degree" in text:
        st.write("✅ Bachelor's Degree")
    elif "bachelor of technology" in text:
        st.write("✅ Bachelor of Technology")
    elif "b.tech" in text:
        st.write("✅ Bachelor of Technology")
    elif "b.e" in text:
        st.write("✅ Bachelor of Engineering")
    else:
        st.write("Education details not found")

    skills = [
        "python",
        "sql",
        "machine learning",
        "html",
        "css",
        "java",
        "c++",
        "dsa",
        "pandas",
        "numpy",
        "streamlit"
    ]

    found_skills = []

    for skill in skills:
        if skill in text:
            found_skills.append(skill)

    score = len(found_skills) * 10

    if score > 100:
        score = 100

    st.subheader("🎯 ATS Score")
    st.progress(score)
    st.write(f"**ATS Score:** {score}/100")

    st.subheader("✅ Skills Found")

    for skill in found_skills:
        st.write("✔", skill)

    st.subheader("💡 Missing Skills")

    for skill in skills:
        if skill not in found_skills:
            st.write("❌", skill)

    st.subheader("💡 Resume Suggestions")

    suggestions = []

    if not email:
        suggestions.append("Add a professional email address.")

    if not phone:
        suggestions.append("Add your phone number.")

    if len(found_skills) < 5:
        suggestions.append("Add more technical skills related to your field.")

    if score < 70:
        suggestions.append("Improve your resume by adding projects, internships, and certifications.")

    if suggestions:
        for suggestion in suggestions:
            st.write("✅", suggestion)
    else:
        st.success("Excellent! Your resume looks good.") 


    st.subheader("💼 Experience")

    if "experience" in text.lower() or "internship" in text.lower():
        st.success("Experience / Internship section found.")
    else:
        st.warning("No experience or internship section found.")


    st.subheader("📜 Certifications")
    if (
        "certificate" in text.lower()
        or "certification" in text.lower()
        or "certifications" in text.lower()
        or "certified" in text.lower()
    ):
        st.success("✅ Certification section found.")
    else:
        st.warning("❌ No certification section found.")


    st.subheader("📋 Missing Sections")
    sections = {
        "Objective": ["objective", "summary", "career objective"],
        "Projects": ["project", "projects"],
        "Skills": ["skills", "technical skills"],
        "Experience": ["experience", "internship"],
        "Certifications": ["certificate", "certification"]
    }

    for section, keywords in sections.items():
        if any(keyword in text.lower() for keyword in keywords):
            st.write(f"✅ {section}")
        else:
            st.write(f"❌ {section}")

    if job_description:
        resume_words = set(text.split())
        jd_words = set(job_description.lower().split())

        if jd_words:
            matched_words = resume_words.intersection(jd_words)

            match_score = int((len(matched_words) / len(jd_words)) * 100)

            st.subheader("🎯 Job Description Match")
            st.success(f"Match Score: {match_score}%")

            missing = jd_words - resume_words

            if missing:
                st.write("❌ Missing Keywords:")
                st.write(", ".join(list(missing)[:20]))

    pdf = generate_pdf(
        email,
        phone,
        score,
        match_score if job_description else 0,
        sections,
        missing if job_description else set()
    )

    st.download_button(
        label="📄 Download PDF Report",
        data=pdf,
        file_name="Resume_Analysis_Report.pdf",
        mime="application/pdf"
    )            